### ISSUE TITLE
Would it be possible to pass an HttpClient?

### ISSUE THREAD

**Issue by vjames19** [parse-community/ParseTwitterUtils-Android#22]
My current concern is that I already have an OkHttpClient instance and most of the time we only need on OkHttpClient per application.

**Comment by grantland** [comment]
Unfortunately we do not support that at the moment.

**Comment by vjames19** [comment]
@grantland Is this something I could do a PR that you guys are willing to merge?

**Comment by grantland** [comment]
I'm not sure this would be something worthwhile. Ideally we would have an API that supports injecting your own OkHttpClient, however, I'd want it to be done in a way that doesn't tightly couple ParseTwitterUtils tightly with a http implementation (be it OkHttp, HttpURLConnection, etc.).

In the end, the client is only really used for a handful of requests and only when Twitter auth is happening, so I don't really see this being that big of a concern.

Instead, #8 seems like the best solution since it would let the client only be created when it's needed, therefore allowing your application to only have a single client 99.9% of the time.

It'd be great to hear your opinions on this, though.

**Comment by Jawnnypoo** [comment]
Feel free to make a PR with this if you would like.
